
import os

def create_minimal_pdf(filename="dummy.pdf"):
    pdf_content = (
        b"%PDF-1.1\n"
        b"% \xe2\xe3\xcf\xd3\n"
        b"1 0 obj\n"
        b"<<\n"
        b"/Type /Catalog\n"
        b"/Pages 2 0 R\n"
        b">>\n"
        b"endobj\n"
        b"2 0 obj\n"
        b"<<\n"
        b"/Type /Pages\n"
        b"/Kids [3 0 R]\n"
        b"/Count 1\n"
        b"/MediaBox [0 0 300 144]\n"
        b">>\n"
        b"endobj\n"
        b"3 0 obj\n"
        b"<<\n"
        b"/Type /Page\n"
        b"/Parent 2 0 R\n"
        b"/Resources <<\n"
        b"/Font <<\n"
        b"/F1 4 0 R\n"
        b">>\n"
        b">>\n"
        b"/Contents 5 0 R\n"
        b">>\n"
        b"endobj\n"
        b"4 0 obj\n"
        b"<<\n"
        b"/Type /Font\n"
        b"/Subtype /Type1\n"
        b"/Name /F1\n"
        b"/BaseFont /Helvetica\n"
        b">>\n"
        b"endobj\n"
        b"5 0 obj\n"
        b"<<\n"
        b"/Length 55\n"
        b">>\n"
        b"stream\n"
        b"BT\n"
        b"/F1 18 Tf\n"
        b"0 0 Td\n"
        b"(This is a test PDF for VeritasAI verification.) Tj\n"
        b"ET\n"
        b"endstream\n"
        b"endobj\n"
        b"xref\n"
        b"0 6\n"
        b"0000000000 65535 f \n"
        b"0000000018 00000 n \n"
        b"0000000077 00000 n \n"
        b"0000000178 00000 n \n"
        b"0000000457 00000 n \n"
        b"0000000565 00000 n \n"
        b"trailer\n"
        b"<<\n"
        b"/Root 1 0 R\n"
        b"/Size 6\n"
        b">>\n"
        b"startxref\n"
        b"665\n"
        b"%%EOF\n"
    )
    
    with open(filename, "wb") as f:
        f.write(pdf_content)
    print(f"Created {filename}")

if __name__ == "__main__":
    create_minimal_pdf()
